export { default as logo1} from "./logo1.webp"
export { default as logo2} from "./logo2.svg"
export { default as logo3} from "./logo3.jpg"
export { default as logo4} from "./logo4.webp"
export { default as logo5} from "./logo5.jpg"
export { default as logo6} from "./logo6.jpg"
