// export { default as img} from "./header_three_bg.png"
// export { default as img1} from "./third_slider_bg01.jpg"
// export { default as img2} from "./third_slider_img01.png"
// export { default as img3} from "./slider_bottom02.png"
export { default as footer} from "./footer_bg.jpg"
export { default as img4} from "./f_blog_thumb01.jpg"
export { default as visa} from "./visa_2.png"
export { default as ae} from "./ae_02.png"
export { default as dis} from "./discover.png"
export { default as strip} from "./stripe.png"
export { default as logo} from "./utkal international white (1).png"
export { default as feature1} from "./close-up-view-dark-fresh-roasted-coffee-beans-coffee-beans-background.jpg"
export { default as feature2} from "./raw-cashews-nuts-bowl-dark-background.jpg"
export { default as feature3} from "./foxnuts.jpg"
export { default as feature4} from "./rice.jpg"
export { default as choose1} from "./choose_bg (1).jpg"
export { default as pro1} from "./project_thumb01.jpg"
export { default as pro2} from "./project_thumb02.jpg"
export { default as pro3} from "./WhatsApp Image 2024-09-19 at 12.16.49 PM.jpeg"
export { default as pro4} from "./project_thumb04.jpg"
export { default as vdo} from "./video_bg02.jpg"
export { default as test} from "./testimonial_bg.jpg"
export { default as test1} from "./logo.jpg"
export { default as header} from "./header.jpeg"
export { default as  post} from "./blog_post_thumb03.jpg"
export { default as Slider1} from "./flat-lay-dried-black-pepper-background.jpg"
export {default as Slider2 }  from "./IMG_1176.jpg"
export{default as Slider3} from "./raw-cashews-nuts-bowl-dark-background.jpg"
export{default as Slider4} from "./ginger-blanket.jpg"
export{default as Slider5} from "./IMG_1263.jpg"
export { default as icon1} from "./third_slider_img01.png"
export {default as icon2} from "./third_slider_img02.png"
export {default as icon3} from "./third_slider_img03.png"
export { default as headerbg} from "./header_three_bg.png"
export { default as bottombg} from "./slider_bottom02.png"
export {default as about} from "./assortment-winter-spices.jpg"
export {default as carde} from "./top-view-bowl-with-seeds.jpg"
export {default as about2} from "./top-view-asian-food-ingredients-mix.jpg"
export {default as ragi} from "./chia-seed.jpg"
export {default as blackrice} from "./black-rice.jpg"
export {default as world} from "./black-rice.jpg"
export {default as ricevarieties} from "./rice.jpg"
export {default as whitebasmatirice} from "./rice-flakes-rice-noodles-rice-bread-rice-top-view.jpg"
export {default as pusarice} from "./top-view-rice-seed-texture.jpg"
export {default as onerice} from "./white-rice.jpg"
export {default as sellarice} from "./top-view-raw-rice-inside-brown-plate-grey-surface.jpg"
export {default as ir64rice} from "./bowl-with-rice-grains-arrangement.jpg"
export {default as SonaMasooriRice} from "./milled-rice-black-bowl-black-cement-floor.jpg"
export {default as mattarice} from "./shop-organic-kerala-matta-rice-online-at-bio-basics-store.webp"
export {default as ponnirice} from "./milled-rice-black-bowl-black-cement-floor.jpg"
export {default as longbrown} from "./top-view-rice-meal-uncooked-rice-with-spoon.jpg"
export {default as basmatibrown} from "./stock-photo-brown-basmati-rice-raw-form-selective-focus_466689-56587.jpg"
export {default as kavunirice} from "./black-seeds-white-background.jpg"
export {default as coffevarieties} from "./green-and-roasted-coffee-1536x864.jpg"
export {default as tejas17} from "./S273-Wrinkle-Chilli-8.png"
export {default as byadgi} from "./byadgi.jpg"
export {default as s4sanam} from "./cayenne-dried-pepper-small-ceramic-bowl.jpg"
export {default as regularturmeric} from "./regular.jpg"
export {default as lakadong} from "./Lakadong-Turmeric-from-the-ground.jpg"
export {default as hasanginger} from "./iris-flower-root-summer-garden-close-up.jpg"
export {default as kandhamalginger} from "./ginger-root-supermarket-closeup-food-background.jpg"
export {default as corn} from "./yellow-corns-background.jpg"
export {default as seedlesstamarind} from "./seedless.webp"
export {default as tamarind} from "./fresh-sweet-ripe-tamarind-dark-surface.jpg"
export {default as seedltamarind} from "./tamarind-seed-kernel1.jpeg"
export {default as cashew} from "./IMG_1289.jpg"
export {default as cashew240} from "./IMG_1288.jpg"
export {default as splitcashew} from "./Cashew_20Split.jpg"
export {default as cashewkernels} from "./swp-cashew-nuts.jpg"
export {default as malabar} from "./black-milled-pepper-corns-as-background-high-quality-photo.jpg"
export {default as tellicherry} from "./close-up-spoon-with-condiment-seeds.jpg"
export {default as organic} from "./closeup-peppercorn-texture.jpg"
export {default as rosted1} from "./roastedcoffee1.jpg"
export {default as rosted2} from "./rostedcoffee2.jpg"
export {default as greenCoffee1} from "./greencoffee1.jpg"
export {default as greenCoffee2} from "./greencoffee3.jpg"
export {default as tur1} from "./tr1.jpeg"